/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ObjectKind =
  | "Справочник"
  | "Документ"
  | "Перечисление"
  | "РегистрНакопления"
  | "РегистрСведений"
  | "РегистрБухгалтерии"
  | "РегистрРасчёта"
  | "ПланСчетов"
  | "ПланВидовХарактеристик"
  | "ПланВидовРасчёта"
  | "БизнесПроцесс"
  | "Задача"
  | "Форма";

/**
 * Карточка механизма. Ключи — латиницей (контракт/код), значения предметной области — на русском. Поле model — типизированное объединение по kind (диспетчер). См. docs/CONCEPT.md §6, §8.
 */
export interface MetaConMechanismCard {
  id: string;
  kind: "РН" | "РС" | "РБ" | "РР" | "БП" | "Форма";
  section: "оперативный" | "бухгалтерский" | "расчёт" | "бизнес-процессы" | "формы";
  skill: string;
  requires_context: string[];
  contributes: {
    objects: string[];
    changes: string[];
  };
  /**
   * @minItems 1
   */
  traps: [
    {
      lure: string;
      correct: string;
      why: string;
    },
    ...{
      lure: string;
      correct: string;
      why: string;
    }[]
  ];
  /**
   * Спека допусков: обязательное / допустимое / дисквалификаторы. По ней грейдятся уровни 1-2.
   */
  tolerance: {
    required_objects: {
      role: string;
      object_kind: ObjectKind;
    }[];
    required_structure: {
      object: string;
      dimensions: string[];
      resources: string[];
    }[];
    allowed: string[];
    disqualifiers: string[];
  };
  levels: {
    "1": Level;
    "2": Level;
    "3"?: Level;
  };
  /**
   * Пулы для рандомизации поверхности. Контент — наш, не из книги.
   */
  render?: {
    nomenclature_pool?: string[];
    period_pool?: string[];
    /**
     * @minItems 2
     * @maxItems 2
     */
    qty_range?: [number, number];
    /**
     * @minItems 2
     * @maxItems 2
     */
    price_range?: [number, number];
    scaffold_template?: string;
  };
  /**
   * Единственный источник истины. Форма тела зависит от kind.
   */
  model: ModelRN | ModelStub;
}
export interface Level {
  projection: string;
  grade: "точное_множество" | "обязательное_ядро" | "эталон_поведение";
  modes?: ("декларатив" | "код" | "поведение")[];
}
export interface ModelRN {
  kind: "РН";
  partners?: ObjectDef[];
  objects: ObjectDef[];
  register: {
    name: string;
    subtype: "остатки" | "обороты" | "остатки_обороты";
    dimensions: Field[];
    resources: Field[];
    attributes?: Field[];
  };
  movements: {
    document: string;
    records: {
      kind: "Приход" | "Расход";
      resources?: {
        [k: string]: unknown;
      };
      algorithm_id?: string;
    }[];
  }[];
}
export interface ObjectDef {
  name: string;
  object_kind: ObjectKind;
  subtype?: string;
  values?: string[];
  fields?: Field[];
  tabular_sections?: {
    name: string;
    fields: string[];
    [k: string]: unknown;
  }[];
}
export interface Field {
  name: string;
  type?: string;
  role?: "измерение" | "ресурс" | "реквизит";
}
/**
 * Заглушка для kind ∈ {РС, РБ, РР, БП, Форма}. Тело дозревает отдельно (CONCEPT §8).
 */
export interface ModelStub {
  kind: "РС" | "РБ" | "РР" | "БП" | "Форма";
  [k: string]: unknown;
}
